export const LoginTypes = {
  GET_LOGIN_LOADING: "GET_LOGIN_LOADING",
  GET_LOGIN_SUCCESS: "GET_LOGIN_SUCCESS",
  GET_LOGIN_FAIL: "GET_LOGIN_FAIL",

  GET_AUTHOR_DETAILS_LOADING: "GET_AUTHOR_DETAILS_LOADING",
  GET_AUTHOR_DETAILS_SUCCESS: "GET_AUTHOR_DETAILS_SUCCESS",
  GET_AUTHOR_DETAILS_FAIL: "GET_AUTHOR_DETAILS_FAIL",

  GET_AUTHOR_SEARCH_LOADING: "GET_AUTHOR_SEARCH_LOADING",
  GET_AUTHOR_SEARCH_SUCCESS: "GET_AUTHOR_SEARCH_SUCCESS",
  GET_AUTHOR_SEARCH_FAIL: "GET_AUTHOR_SEARCH_FAIL",

  GET_BOOKS_DETAILS_LOADING: "GET_BOOKS_DETAILS_LOADING",
  GET_BOOKS_DETAILS_SUCCESS: "GET_BOOKS_DETAILS_SUCCESS",
  GET_BOOKS_DETAILS_FAIL: "GET_BOOKS_DETAILS_FAIL",

  GET_AUTHOR_BOOKS_LOADING: "GET_AUTHOR_BOOKS_LOADING",
  GET_AUTHOR_BOOKS_SUCCESS: "GET_AUTHOR_BOOKS_SUCCESS",
  GET_AUTHOR_BOOKS_FAIL: "GET_AUTHOR_BOOKS_FAIL",

  ADD_AUTHOR_BOOKS_LOADING:'ADD_AUTHOR_BOOKS_LOADING',
  ADD_AUTHOR_BOOKS_SUCCESS:'ADD_AUTHOR_BOOKS_SUCCESS'
}